--- backup/platform/snapshot.sql	2024-05-31 14:14:38.027744790 +0000
+++ snapshots/platform/snapshot.sql	2024-05-31 14:14:26.000000000 +0000
@@ -5,3 +5,3253 @@
 -- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
 -- Dumped by pg_dump version 16.3 (Debian 16.3-1.pgdg110+1)
 
+SET statement_timeout = 0;
+SET lock_timeout = 0;
+SET idle_in_transaction_session_timeout = 0;
+SET client_encoding = 'UTF8';
+SET standard_conforming_strings = on;
+SELECT pg_catalog.set_config('search_path', '', false);
+SET check_function_bodies = false;
+SET xmloption = content;
+SET client_min_messages = warning;
+SET row_security = off;
+
+--
+-- Name: platform; Type: SCHEMA; Schema: -; Owner: -
+--
+
+CREATE SCHEMA platform;
+
+
+SET default_tablespace = '';
+
+SET default_table_access_method = heap;
+
+--
+-- Name: asset; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset (
+    id integer NOT NULL,
+    name character varying NOT NULL,
+    region_id integer NOT NULL,
+    resource_id character varying,
+    data jsonb DEFAULT '{}'::jsonb NOT NULL,
+    customer_id integer NOT NULL,
+    resource_id_load character varying,
+    parent_asset_id integer,
+    root_asset_id integer,
+    asset_type_id integer NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    created_by integer NOT NULL,
+    asset_key uuid DEFAULT platform.uuid_generate_v4() NOT NULL,
+    valid_start timestamp with time zone DEFAULT '2010-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    valid_end timestamp with time zone DEFAULT '9999-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    asset_mode_id smallint NOT NULL
+);
+
+
+--
+-- Name: asset_data; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_data (
+    id integer NOT NULL,
+    asset_id integer NOT NULL,
+    tag character varying NOT NULL,
+    data jsonb NOT NULL,
+    start_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    created_by integer NOT NULL,
+    deleted boolean NOT NULL,
+    deleted_by integer,
+    asset_data_type_id smallint DEFAULT 1
+);
+
+
+--
+-- Name: asset_data_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.asset_data_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_data_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_data_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    schema json,
+    asset_type_id integer,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE asset_data_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.asset_data_type IS 'This table holds information on different types of asset data';
+
+
+--
+-- Name: asset_data_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_data_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.asset_data_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.asset_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_market_product_xref; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_market_product_xref (
+    id integer NOT NULL,
+    asset_id integer NOT NULL,
+    market_product_id integer NOT NULL,
+    valid_start timestamp with time zone DEFAULT '2010-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    valid_end timestamp with time zone DEFAULT '9999-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    created_by integer NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    modified_by integer NOT NULL,
+    modified_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE asset_market_product_xref; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.asset_market_product_xref IS 'This table records which products the asset enrolled into.';
+
+
+--
+-- Name: asset_market_product_xref_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_market_product_xref ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.asset_market_product_xref_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_meter; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_meter (
+    id integer NOT NULL,
+    asset_meter_key uuid DEFAULT platform.uuid_generate_v4(),
+    asset_id integer NOT NULL,
+    asset_meter_type_id smallint,
+    name character varying NOT NULL,
+    meter_reading_frequency integer,
+    meter_upload_frequency integer,
+    effective_time timestamp with time zone,
+    expiration_time timestamp with time zone,
+    status smallint,
+    valid_start timestamp with time zone DEFAULT '2010-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    valid_end timestamp with time zone DEFAULT '9999-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    created_by integer,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE asset_meter; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.asset_meter IS 'This table defines meter (telemetry stream) under each asset.';
+
+
+--
+-- Name: asset_meter_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_meter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.asset_meter_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_meter_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_meter_type (
+    id integer NOT NULL,
+    name character varying,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE asset_meter_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.asset_meter_type IS 'This table defines all the possible asset meter (telemetry stream) type, like BESS, SCADA, etc.';
+
+
+--
+-- Name: asset_meter_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_meter_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.asset_meter_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_mode; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_mode (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE asset_mode; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.asset_mode IS 'This table defined all the possible asset statuses in Mosaic Platform, like active, inactive.';
+
+
+--
+-- Name: asset_mode_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_mode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.asset_mode_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_product_data; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_product_data (
+    id integer NOT NULL,
+    asset_id integer NOT NULL,
+    product_id integer NOT NULL,
+    tag character varying NOT NULL,
+    data jsonb NOT NULL,
+    start_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    created_by integer NOT NULL,
+    deleted boolean NOT NULL,
+    deleted_by integer
+);
+
+
+--
+-- Name: asset_product_data_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_product_data ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.asset_product_data_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_telemetry_data; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_telemetry_data (
+    id bigint NOT NULL,
+    asset_meter_id integer,
+    telemetry_value_type_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    read_time timestamp with time zone,
+    value double precision,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: asset_telemetry_data_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_telemetry_data ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.asset_telemetry_data_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.asset_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    asset_registration_type_id integer,
+    asset_schema jsonb,
+    asset_config_schema jsonb
+);
+
+
+--
+-- Name: TABLE asset_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.asset_type IS 'This table defined all the possible asset type, like wind, solar, battery and etc..';
+
+
+--
+-- Name: asset_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.asset_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.asset_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: award; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.award (
+    id integer NOT NULL,
+    market_task_id integer,
+    asset_id integer NOT NULL,
+    product_id integer,
+    resource_type_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    award_quantity double precision NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: award_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.award ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.award_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: bid; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.bid (
+    id integer NOT NULL,
+    market_task_id integer,
+    asset_id integer NOT NULL,
+    resource_type_id smallint NOT NULL,
+    product_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: bid_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.bid ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.bid_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: bid_segment; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.bid_segment (
+    id integer NOT NULL,
+    bid_id integer NOT NULL,
+    interval_start timestamp with time zone,
+    interval_end timestamp with time zone,
+    segment smallint NOT NULL,
+    price double precision,
+    quantity double precision,
+    prep_time timestamp with time zone,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: bid_segment_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.bid_segment ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.bid_segment_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: configuration; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.configuration (
+    asset_id integer NOT NULL,
+    market_id smallint NOT NULL,
+    hour_ending smallint NOT NULL,
+    start_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    data jsonb NOT NULL,
+    created_by integer NOT NULL,
+    deleted boolean NOT NULL,
+    deleted_by integer NOT NULL
+);
+
+
+--
+-- Name: cop_limit; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.cop_limit (
+    id integer NOT NULL,
+    market_task_id integer,
+    asset_id integer NOT NULL,
+    resource_type_id smallint NOT NULL,
+    limit_type_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    cop_limit_value double precision NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: cop_limit_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.cop_limit ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.cop_limit_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: cop_limit_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.cop_limit_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE cop_limit_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.cop_limit_type IS 'This table defined all the cop limit types.';
+
+
+--
+-- Name: cop_limit_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.cop_limit_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.cop_limit_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: cop_product; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.cop_product (
+    id integer NOT NULL,
+    market_task_id integer,
+    asset_id integer NOT NULL,
+    resource_type_id smallint NOT NULL,
+    product_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    cop_product_value double precision NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: cop_product_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.cop_product ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.cop_product_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: cop_status; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.cop_status (
+    id integer NOT NULL,
+    market_task_id integer,
+    asset_id integer NOT NULL,
+    resource_type_id smallint NOT NULL,
+    cop_status_type_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: cop_status_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.cop_status ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.cop_status_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: cop_status_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.cop_status_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: cop_status_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.cop_status_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.cop_status_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: host_customer; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.host_customer (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    updated_on timestamp with time zone DEFAULT now() NOT NULL,
+    salesforce_record_id character varying,
+    quickbase_record_id integer,
+    scheduling_coordinator_id character varying
+);
+
+
+--
+-- Name: host_customer_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.host_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.host_customer_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: input_cop_limit; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.input_cop_limit (
+    market_task_id integer NOT NULL,
+    cop_limit_id integer NOT NULL
+);
+
+
+--
+-- Name: input_cop_product; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.input_cop_product (
+    market_task_id integer NOT NULL,
+    cop_product_id integer NOT NULL
+);
+
+
+--
+-- Name: input_cop_status; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.input_cop_status (
+    market_task_id integer NOT NULL,
+    cop_status_id integer NOT NULL
+);
+
+
+--
+-- Name: interval_soc; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.interval_soc (
+    id integer NOT NULL,
+    market_task_id integer,
+    asset_id integer NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    soc_type_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    soc_value double precision NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: interval_soc_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.interval_soc ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.interval_soc_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: iso; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.iso (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    display_name character varying NOT NULL,
+    time_zone character varying NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    created_by integer NOT NULL,
+    last_modified_on timestamp with time zone DEFAULT now() NOT NULL,
+    last_modified_by integer NOT NULL
+);
+
+
+--
+-- Name: TABLE iso; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.iso IS 'This table defined ISO/RTO and some of its related parameters';
+
+
+--
+-- Name: iso_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.iso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.iso_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    data jsonb DEFAULT '{}'::jsonb NOT NULL,
+    description character varying,
+    market_type_id smallint NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE market; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.market IS 'This table defined all the markets that ISO/RTO provided.';
+
+
+--
+-- Name: market_agent; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market_agent (
+    id smallint NOT NULL,
+    iso_id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    market_agent_code character varying NOT NULL,
+    market_participant_code character varying,
+    api_user character varying,
+    password character varying,
+    certificate character varying,
+    level smallint NOT NULL,
+    created_by smallint NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    last_modified_by smallint NOT NULL,
+    last_modified_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE market_agent; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.market_agent IS 'This table is used to maintain data object for QSE, SC, market participant and etc., they are called different name in different ISO/RTOs.';
+
+
+--
+-- Name: market_agent_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market_agent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.market_agent_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.market_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market_job; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market_job (
+    id integer NOT NULL,
+    scenario_id integer,
+    market_type_id smallint NOT NULL,
+    market_job_type_id smallint NOT NULL,
+    associated_run_id smallint,
+    job_run_start timestamp with time zone,
+    job_run_end timestamp with time zone,
+    job_run_status character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: market_job_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market_job ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.market_job_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market_job_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market_job_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: market_job_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market_job_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.market_job_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market_permission_grants; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market_permission_grants (
+    id integer NOT NULL,
+    user_id integer NOT NULL,
+    permission_id character varying(255) NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    created_by integer
+);
+
+
+--
+-- Name: market_permission_grants_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market_permission_grants ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.market_permission_grants_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market_product_xref; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market_product_xref (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    iso_id smallint NOT NULL,
+    market_id smallint NOT NULL,
+    product_id smallint NOT NULL,
+    description character varying,
+    valid_start timestamp with time zone DEFAULT '2010-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    valid_end timestamp with time zone DEFAULT '9999-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    last_modified_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE market_product_xref; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.market_product_xref IS 'This table defines the market/product combination that ISO provides.';
+
+
+--
+-- Name: market_product_xref_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market_product_xref ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.market_product_xref_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market_task; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market_task (
+    id integer NOT NULL,
+    market_job_id integer,
+    task_type_id smallint NOT NULL,
+    forecast_input_id smallint,
+    task_horizon_start timestamp with time zone NOT NULL,
+    task_horizon_end timestamp with time zone NOT NULL,
+    task_run_start timestamp with time zone NOT NULL,
+    task_run_end timestamp with time zone NOT NULL,
+    task_run_status character varying NOT NULL,
+    log character varying,
+    input_data jsonb,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: market_task_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market_task ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.market_task_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: market_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.market_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: market_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.market_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.market_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: obligation; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.obligation (
+    id integer NOT NULL,
+    market_task_id integer NOT NULL,
+    cop_product_id integer,
+    award_id integer,
+    region_award_id integer,
+    CONSTRAINT obligation_check CHECK (((cop_product_id IS NOT NULL) <> ((award_id IS NOT NULL) OR (region_award_id IS NOT NULL))))
+);
+
+
+--
+-- Name: obligation_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.obligation ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.obligation_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: offer_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.offer_type (
+    id integer NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE offer_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.offer_type IS 'This tables stores the kinds of Award Offer Types available in the market';
+
+
+--
+-- Name: offer_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.offer_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.offer_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: permissions; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.permissions (
+    id character varying(255) NOT NULL,
+    name character varying(255) NOT NULL,
+    description character varying,
+    market_assignable boolean NOT NULL,
+    customer_assignable boolean NOT NULL,
+    asset_assignable boolean NOT NULL,
+    requires_internal_admin boolean NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    created_by integer,
+    CONSTRAINT permissions_chk_at_least_one_assignable CHECK (((market_assignable = true) OR (customer_assignable = true) OR (asset_assignable = true)))
+);
+
+
+--
+-- Name: process_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.process_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: process_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.process_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.process_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: product; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.product (
+    id smallint NOT NULL,
+    iso_id smallint DEFAULT 11 NOT NULL,
+    market_id integer NOT NULL,
+    product_type_id smallint NOT NULL,
+    name character varying NOT NULL,
+    data jsonb DEFAULT '{}'::jsonb NOT NULL,
+    description character varying,
+    valid_start timestamp with time zone DEFAULT '2010-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    valid_end timestamp with time zone DEFAULT '9999-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE product; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.product IS 'This table defined general products used in different ISOs/RTOs.';
+
+
+--
+-- Name: product_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.product_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: product_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.product_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE product_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.product_type IS 'This table defined the types of the product.';
+
+
+--
+-- Name: product_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.product_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.product_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: region; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.region (
+    id integer NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    data jsonb DEFAULT '{}'::jsonb NOT NULL,
+    iso_id smallint DEFAULT 11 NOT NULL
+);
+
+
+--
+-- Name: region_award; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.region_award (
+    id integer NOT NULL,
+    market_agent_id integer NOT NULL,
+    region_id integer NOT NULL,
+    market_task_id integer,
+    product_id integer NOT NULL,
+    process_type_id smallint NOT NULL,
+    bid_id character varying NOT NULL,
+    offer_type_id smallint NOT NULL,
+    award_quantity double precision NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE region_award; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.region_award IS 'This table stores Awardeds at Region level';
+
+
+--
+-- Name: region_award_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.region_award ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.region_award_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: region_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.region ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.region_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: registration_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.registration_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE registration_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.registration_type IS 'This table defines all the possible registration types in the asset tree including asset_group, asset, and etc...';
+
+
+--
+-- Name: registration_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.registration_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.registration_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: resource; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.resource (
+    id integer NOT NULL,
+    name character varying NOT NULL,
+    resource_type_id smallint NOT NULL,
+    market_agent_id smallint NOT NULL,
+    asset_id integer NOT NULL,
+    created_by smallint NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    last_modified_by smallint NOT NULL,
+    last_modified_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE resource; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.resource IS 'This table stores all the resources registered in the ISO/RTO that we are providing service with.';
+
+
+--
+-- Name: resource_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.resource_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: resource_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.resource_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE resource_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.resource_type IS 'This table defined all the possible resource type, which defined by ISO/RTO.';
+
+
+--
+-- Name: resource_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.resource_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.resource_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: settlement; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.settlement (
+    id integer NOT NULL,
+    market_task_id integer,
+    asset_id integer NOT NULL,
+    product_id integer,
+    resource_type_id smallint NOT NULL,
+    process_type_id smallint NOT NULL,
+    settlement_amount double precision NOT NULL,
+    interval_start timestamp with time zone NOT NULL,
+    interval_end timestamp with time zone NOT NULL,
+    prep_time timestamp with time zone NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: settlement_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.settlement ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
+    SEQUENCE NAME platform.settlement_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: soc_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.soc_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE soc_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.soc_type IS 'This table defined soc types.';
+
+
+--
+-- Name: soc_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.soc_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.soc_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: task_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.task_type (
+    id smallint NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: task_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.task_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.task_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: telemetry_value_type; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.telemetry_value_type (
+    id integer NOT NULL,
+    name character varying NOT NULL,
+    description character varying,
+    created_on timestamp with time zone DEFAULT now() NOT NULL
+);
+
+
+--
+-- Name: TABLE telemetry_value_type; Type: COMMENT; Schema: platform; Owner: -
+--
+
+COMMENT ON TABLE platform.telemetry_value_type IS 'This table defines all the possible telemetry value types Mosaic is handling, like SOC, SOE, etc.';
+
+
+--
+-- Name: telemetry_value_type_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.telemetry_value_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.telemetry_value_type_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: users; Type: TABLE; Schema: platform; Owner: -
+--
+
+CREATE TABLE platform.users (
+    id integer NOT NULL,
+    name character varying NOT NULL,
+    email character varying NOT NULL,
+    title character varying NOT NULL,
+    preferences jsonb NOT NULL,
+    created_on timestamp with time zone DEFAULT now() NOT NULL,
+    is_active boolean DEFAULT true NOT NULL,
+    has_registered boolean DEFAULT false NOT NULL,
+    updated_on timestamp with time zone DEFAULT now(),
+    phone_number character varying,
+    has_mfa boolean DEFAULT false,
+    slack_user_id character varying,
+    external_user_id character varying
+);
+
+
+--
+-- Name: users_id_seq; Type: SEQUENCE; Schema: platform; Owner: -
+--
+
+ALTER TABLE platform.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
+    SEQUENCE NAME platform.users_id_seq
+    START WITH 1
+    INCREMENT BY 1
+    NO MINVALUE
+    NO MAXVALUE
+    CACHE 1
+);
+
+
+--
+-- Name: asset_data asset_data_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_data
+    ADD CONSTRAINT asset_data_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset_data_type asset_data_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_data_type
+    ADD CONSTRAINT asset_data_type_name_key UNIQUE (name);
+
+
+--
+-- Name: asset_data_type asset_data_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_data_type
+    ADD CONSTRAINT asset_data_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset_market_product_xref asset_market_product_xref_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_market_product_xref
+    ADD CONSTRAINT asset_market_product_xref_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset_meter asset_meter_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_meter
+    ADD CONSTRAINT asset_meter_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset_meter_type asset_meter_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_meter_type
+    ADD CONSTRAINT asset_meter_type_name_key UNIQUE (name);
+
+
+--
+-- Name: asset_meter_type asset_meter_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_meter_type
+    ADD CONSTRAINT asset_meter_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset_mode asset_mode_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_mode
+    ADD CONSTRAINT asset_mode_name_key UNIQUE (name);
+
+
+--
+-- Name: asset_mode asset_mode_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_mode
+    ADD CONSTRAINT asset_mode_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset asset_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset_product_data asset_product_data_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_product_data
+    ADD CONSTRAINT asset_product_data_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset asset_resource_id_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_resource_id_key UNIQUE (resource_id);
+
+
+--
+-- Name: asset asset_resource_id_load_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_resource_id_load_key UNIQUE (resource_id_load);
+
+
+--
+-- Name: asset_telemetry_data asset_telemetry_data_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_telemetry_data
+    ADD CONSTRAINT asset_telemetry_data_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: asset_type asset_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_type
+    ADD CONSTRAINT asset_type_name_key UNIQUE (name);
+
+
+--
+-- Name: asset_type asset_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_type
+    ADD CONSTRAINT asset_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: award award_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.award
+    ADD CONSTRAINT award_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: bid bid_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.bid
+    ADD CONSTRAINT bid_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: bid_segment bid_segment_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.bid_segment
+    ADD CONSTRAINT bid_segment_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: configuration configuration_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.configuration
+    ADD CONSTRAINT configuration_pkey PRIMARY KEY (asset_id, start_time, hour_ending, market_id, created_on);
+
+
+--
+-- Name: cop_limit cop_limit_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit
+    ADD CONSTRAINT cop_limit_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: cop_limit_type cop_limit_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit_type
+    ADD CONSTRAINT cop_limit_type_name_key UNIQUE (name);
+
+
+--
+-- Name: cop_limit_type cop_limit_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit_type
+    ADD CONSTRAINT cop_limit_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: cop_product cop_product_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_product
+    ADD CONSTRAINT cop_product_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: cop_status cop_status_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status
+    ADD CONSTRAINT cop_status_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: cop_status_type cop_status_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status_type
+    ADD CONSTRAINT cop_status_type_name_key UNIQUE (name);
+
+
+--
+-- Name: cop_status_type cop_status_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status_type
+    ADD CONSTRAINT cop_status_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: host_customer host_customer_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.host_customer
+    ADD CONSTRAINT host_customer_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: input_cop_limit input_cop_limit_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_limit
+    ADD CONSTRAINT input_cop_limit_pkey PRIMARY KEY (market_task_id, cop_limit_id);
+
+
+--
+-- Name: input_cop_product input_cop_product_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_product
+    ADD CONSTRAINT input_cop_product_pkey PRIMARY KEY (market_task_id, cop_product_id);
+
+
+--
+-- Name: input_cop_status input_cop_status_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_status
+    ADD CONSTRAINT input_cop_status_pkey PRIMARY KEY (market_task_id, cop_status_id);
+
+
+--
+-- Name: interval_soc interval_soc_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.interval_soc
+    ADD CONSTRAINT interval_soc_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: iso iso_display_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.iso
+    ADD CONSTRAINT iso_display_name_key UNIQUE (display_name);
+
+
+--
+-- Name: iso iso_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.iso
+    ADD CONSTRAINT iso_name_key UNIQUE (name);
+
+
+--
+-- Name: iso iso_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.iso
+    ADD CONSTRAINT iso_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market_agent market_agent_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_agent
+    ADD CONSTRAINT market_agent_name_key UNIQUE (name);
+
+
+--
+-- Name: market_agent market_agent_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_agent
+    ADD CONSTRAINT market_agent_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market_job market_job_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_job
+    ADD CONSTRAINT market_job_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market_job_type market_job_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_job_type
+    ADD CONSTRAINT market_job_type_name_key UNIQUE (name);
+
+
+--
+-- Name: market_job_type market_job_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_job_type
+    ADD CONSTRAINT market_job_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market market_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market
+    ADD CONSTRAINT market_name_key UNIQUE (name);
+
+
+--
+-- Name: market_permission_grants market_permission_grants_foreign_keys_unique; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_permission_grants
+    ADD CONSTRAINT market_permission_grants_foreign_keys_unique UNIQUE (user_id, permission_id);
+
+
+--
+-- Name: market_permission_grants market_permission_grants_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_permission_grants
+    ADD CONSTRAINT market_permission_grants_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market market_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market
+    ADD CONSTRAINT market_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market_product_xref market_product_xref_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_product_xref
+    ADD CONSTRAINT market_product_xref_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market_task market_task_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_task
+    ADD CONSTRAINT market_task_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: market_type market_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_type
+    ADD CONSTRAINT market_type_name_key UNIQUE (name);
+
+
+--
+-- Name: market_type market_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_type
+    ADD CONSTRAINT market_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: obligation obligation_market_task_id_award_id_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_market_task_id_award_id_key UNIQUE (market_task_id, award_id);
+
+
+--
+-- Name: obligation obligation_market_task_id_cop_product_id_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_market_task_id_cop_product_id_key UNIQUE (market_task_id, cop_product_id);
+
+
+--
+-- Name: obligation obligation_market_task_id_region_award_id_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_market_task_id_region_award_id_key UNIQUE (market_task_id, region_award_id);
+
+
+--
+-- Name: obligation obligation_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: offer_type offer_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.offer_type
+    ADD CONSTRAINT offer_type_name_key UNIQUE (name);
+
+
+--
+-- Name: offer_type offer_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.offer_type
+    ADD CONSTRAINT offer_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.permissions
+    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: process_type process_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.process_type
+    ADD CONSTRAINT process_type_name_key UNIQUE (name);
+
+
+--
+-- Name: process_type process_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.process_type
+    ADD CONSTRAINT process_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: product product_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.product
+    ADD CONSTRAINT product_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: product_type product_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.product_type
+    ADD CONSTRAINT product_type_name_key UNIQUE (name);
+
+
+--
+-- Name: product_type product_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.product_type
+    ADD CONSTRAINT product_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: region_award region_award_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region_award
+    ADD CONSTRAINT region_award_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: region region_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region
+    ADD CONSTRAINT region_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: registration_type registration_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.registration_type
+    ADD CONSTRAINT registration_type_name_key UNIQUE (name);
+
+
+--
+-- Name: registration_type registration_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.registration_type
+    ADD CONSTRAINT registration_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: resource resource_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.resource
+    ADD CONSTRAINT resource_name_key UNIQUE (name);
+
+
+--
+-- Name: resource resource_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.resource
+    ADD CONSTRAINT resource_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: resource_type resource_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.resource_type
+    ADD CONSTRAINT resource_type_name_key UNIQUE (name);
+
+
+--
+-- Name: resource_type resource_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.resource_type
+    ADD CONSTRAINT resource_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: settlement settlement_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.settlement
+    ADD CONSTRAINT settlement_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: soc_type soc_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.soc_type
+    ADD CONSTRAINT soc_type_name_key UNIQUE (name);
+
+
+--
+-- Name: soc_type soc_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.soc_type
+    ADD CONSTRAINT soc_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: task_type task_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.task_type
+    ADD CONSTRAINT task_type_name_key UNIQUE (name);
+
+
+--
+-- Name: task_type task_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.task_type
+    ADD CONSTRAINT task_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: telemetry_value_type telemetry_value_type_name_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.telemetry_value_type
+    ADD CONSTRAINT telemetry_value_type_name_key UNIQUE (name);
+
+
+--
+-- Name: telemetry_value_type telemetry_value_type_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.telemetry_value_type
+    ADD CONSTRAINT telemetry_value_type_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: users users_email_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.users
+    ADD CONSTRAINT users_email_key UNIQUE (email);
+
+
+--
+-- Name: users users_external_user_id_key; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.users
+    ADD CONSTRAINT users_external_user_id_key UNIQUE (external_user_id);
+
+
+--
+-- Name: users users_pkey; Type: CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.users
+    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
+
+
+--
+-- Name: apd_asset_id_product_id_tag_idx; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX apd_asset_id_product_id_tag_idx ON platform.asset_product_data USING btree (asset_id, product_id, tag);
+
+
+--
+-- Name: apd_asset_id_tag_idx; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX apd_asset_id_tag_idx ON platform.asset_product_data USING btree (asset_id, tag);
+
+
+--
+-- Name: asset_data_asset_id_tag_idx; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX asset_data_asset_id_tag_idx ON platform.asset_data USING btree (asset_id, tag);
+
+
+--
+-- Name: asset_name; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE UNIQUE INDEX asset_name ON platform.asset USING btree (name);
+
+
+--
+-- Name: asset_region_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX asset_region_id ON platform.asset USING btree (region_id);
+
+
+--
+-- Name: idx_asset_customer_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_asset_customer_id ON platform.asset USING btree (customer_id);
+
+
+--
+-- Name: idx_award_created_on; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_award_created_on ON platform.award USING btree (created_on);
+
+
+--
+-- Name: idx_award_interval_end; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_award_interval_end ON platform.award USING btree (interval_end);
+
+
+--
+-- Name: idx_award_interval_start; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_award_interval_start ON platform.award USING btree (interval_start);
+
+
+--
+-- Name: idx_award_resource_type; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_award_resource_type ON platform.award USING btree (resource_type_id);
+
+
+--
+-- Name: idx_bid_asset_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_bid_asset_id ON platform.bid USING btree (asset_id);
+
+
+--
+-- Name: idx_bid_created_on; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_bid_created_on ON platform.bid USING btree (created_on);
+
+
+--
+-- Name: idx_bid_interval_end; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_bid_interval_end ON platform.bid USING btree (interval_end);
+
+
+--
+-- Name: idx_bid_interval_start; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_bid_interval_start ON platform.bid USING btree (interval_start);
+
+
+--
+-- Name: idx_bid_segment_bid_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_bid_segment_bid_id ON platform.bid_segment USING btree (bid_id);
+
+
+--
+-- Name: idx_cop_limit_created_on; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_limit_created_on ON platform.cop_limit USING btree (created_on);
+
+
+--
+-- Name: idx_cop_limit_interval_end; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_limit_interval_end ON platform.cop_limit USING btree (interval_end);
+
+
+--
+-- Name: idx_cop_limit_interval_start; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_limit_interval_start ON platform.cop_limit USING btree (interval_start);
+
+
+--
+-- Name: idx_cop_limit_limit_type; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_limit_limit_type ON platform.cop_limit USING btree (limit_type_id);
+
+
+--
+-- Name: idx_cop_limit_resource_type; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_limit_resource_type ON platform.cop_limit USING btree (resource_type_id);
+
+
+--
+-- Name: idx_cop_product_created_on; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_product_created_on ON platform.cop_product USING btree (created_on);
+
+
+--
+-- Name: idx_cop_product_interval_end; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_product_interval_end ON platform.cop_product USING btree (interval_end);
+
+
+--
+-- Name: idx_cop_product_interval_start; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_product_interval_start ON platform.cop_product USING btree (interval_start);
+
+
+--
+-- Name: idx_cop_product_resource_type; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_product_resource_type ON platform.cop_product USING btree (resource_type_id);
+
+
+--
+-- Name: idx_cop_status_created_on; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_status_created_on ON platform.cop_status USING btree (created_on);
+
+
+--
+-- Name: idx_cop_status_interval_end; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_status_interval_end ON platform.cop_status USING btree (interval_end);
+
+
+--
+-- Name: idx_cop_status_interval_start; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_status_interval_start ON platform.cop_status USING btree (interval_start);
+
+
+--
+-- Name: idx_cop_status_resource_type; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_cop_status_resource_type ON platform.cop_status USING btree (resource_type_id);
+
+
+--
+-- Name: idx_customer_quickbase_record_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE UNIQUE INDEX idx_customer_quickbase_record_id ON platform.host_customer USING btree (quickbase_record_id);
+
+
+--
+-- Name: idx_customer_salesforce_record_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE UNIQUE INDEX idx_customer_salesforce_record_id ON platform.host_customer USING btree (salesforce_record_id);
+
+
+--
+-- Name: idx_market_permission_grants_permission_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_market_permission_grants_permission_id ON platform.market_permission_grants USING btree (permission_id);
+
+
+--
+-- Name: idx_market_permission_grants_user_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_market_permission_grants_user_id ON platform.market_permission_grants USING btree (user_id);
+
+
+--
+-- Name: idx_market_permission_grants_user_id_permission_id; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_market_permission_grants_user_id_permission_id ON platform.market_permission_grants USING btree (user_id, permission_id);
+
+
+--
+-- Name: idx_market_task_created_on; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_market_task_created_on ON platform.market_task USING btree (created_on);
+
+
+--
+-- Name: idx_market_task_task_run_end; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_market_task_task_run_end ON platform.market_task USING btree (task_run_end);
+
+
+--
+-- Name: idx_market_task_task_run_start; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_market_task_task_run_start ON platform.market_task USING btree (task_run_start);
+
+
+--
+-- Name: idx_market_task_task_run_status; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_market_task_task_run_status ON platform.market_task USING btree (task_run_status);
+
+
+--
+-- Name: idx_read_time; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_read_time ON platform.asset_telemetry_data USING btree (read_time);
+
+
+--
+-- Name: idx_settlement_created_on; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_settlement_created_on ON platform.settlement USING btree (created_on);
+
+
+--
+-- Name: idx_settlement_interval_end; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_settlement_interval_end ON platform.settlement USING btree (interval_end);
+
+
+--
+-- Name: idx_settlement_interval_start; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_settlement_interval_start ON platform.settlement USING btree (interval_start);
+
+
+--
+-- Name: idx_settlement_resource_type; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX idx_settlement_resource_type ON platform.settlement USING btree (resource_type_id);
+
+
+--
+-- Name: product_market_id_idx; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX product_market_id_idx ON platform.product USING btree (market_id);
+
+
+--
+-- Name: product_name_idx; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE INDEX product_name_idx ON platform.product USING btree (name);
+
+
+--
+-- Name: region_name; Type: INDEX; Schema: platform; Owner: -
+--
+
+CREATE UNIQUE INDEX region_name ON platform.region USING btree (name);
+
+
+--
+-- Name: asset asset_asset_mode_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_asset_mode_id_fkey FOREIGN KEY (asset_mode_id) REFERENCES platform.asset_mode(id);
+
+
+--
+-- Name: asset asset_asset_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_asset_type_id_fkey FOREIGN KEY (asset_type_id) REFERENCES platform.asset_type(id);
+
+
+--
+-- Name: asset asset_created_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_created_by_fkey FOREIGN KEY (created_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: asset asset_customer_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES platform.host_customer(id);
+
+
+--
+-- Name: asset_data asset_data_asset_data_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_data
+    ADD CONSTRAINT asset_data_asset_data_type_id_fkey FOREIGN KEY (asset_data_type_id) REFERENCES platform.asset_data_type(id);
+
+
+--
+-- Name: asset_data asset_data_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_data
+    ADD CONSTRAINT asset_data_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: asset_data asset_data_created_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_data
+    ADD CONSTRAINT asset_data_created_by_fkey FOREIGN KEY (created_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: asset_data asset_data_deleted_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_data
+    ADD CONSTRAINT asset_data_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: asset_market_product_xref asset_market_product_xref_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_market_product_xref
+    ADD CONSTRAINT asset_market_product_xref_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: asset_market_product_xref asset_market_product_xref_created_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_market_product_xref
+    ADD CONSTRAINT asset_market_product_xref_created_by_fkey FOREIGN KEY (created_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: asset_market_product_xref asset_market_product_xref_market_product_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_market_product_xref
+    ADD CONSTRAINT asset_market_product_xref_market_product_id_fkey FOREIGN KEY (market_product_id) REFERENCES platform.market_product_xref(id);
+
+
+--
+-- Name: asset_market_product_xref asset_market_product_xref_modified_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_market_product_xref
+    ADD CONSTRAINT asset_market_product_xref_modified_by_fkey FOREIGN KEY (modified_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: asset_meter asset_meter_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_meter
+    ADD CONSTRAINT asset_meter_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: asset_meter asset_meter_asset_meter_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_meter
+    ADD CONSTRAINT asset_meter_asset_meter_type_id_fkey FOREIGN KEY (asset_meter_type_id) REFERENCES platform.asset_meter_type(id);
+
+
+--
+-- Name: asset asset_parent_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_parent_asset_id_fkey FOREIGN KEY (parent_asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: asset_product_data asset_product_data_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_product_data
+    ADD CONSTRAINT asset_product_data_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: asset_product_data asset_product_data_created_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_product_data
+    ADD CONSTRAINT asset_product_data_created_by_fkey FOREIGN KEY (created_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: asset_product_data asset_product_data_deleted_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_product_data
+    ADD CONSTRAINT asset_product_data_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: asset_product_data asset_product_data_product_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_product_data
+    ADD CONSTRAINT asset_product_data_product_id_fkey FOREIGN KEY (product_id) REFERENCES platform.product(id);
+
+
+--
+-- Name: asset asset_region_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_region_id_fkey FOREIGN KEY (region_id) REFERENCES platform.region(id);
+
+
+--
+-- Name: asset asset_root_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset
+    ADD CONSTRAINT asset_root_asset_id_fkey FOREIGN KEY (root_asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: asset_telemetry_data asset_telemetry_data_asset_meter_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_telemetry_data
+    ADD CONSTRAINT asset_telemetry_data_asset_meter_id_fkey FOREIGN KEY (asset_meter_id) REFERENCES platform.asset_meter(id);
+
+
+--
+-- Name: asset_telemetry_data asset_telemetry_data_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_telemetry_data
+    ADD CONSTRAINT asset_telemetry_data_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: asset_telemetry_data asset_telemetry_data_telemetry_value_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_telemetry_data
+    ADD CONSTRAINT asset_telemetry_data_telemetry_value_type_id_fkey FOREIGN KEY (telemetry_value_type_id) REFERENCES platform.telemetry_value_type(id);
+
+
+--
+-- Name: asset_type asset_type_asset_registration_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.asset_type
+    ADD CONSTRAINT asset_type_asset_registration_type_id_fkey FOREIGN KEY (asset_registration_type_id) REFERENCES platform.registration_type(id);
+
+
+--
+-- Name: award award_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.award
+    ADD CONSTRAINT award_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: award award_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.award
+    ADD CONSTRAINT award_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: award award_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.award
+    ADD CONSTRAINT award_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: award award_resource_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.award
+    ADD CONSTRAINT award_resource_type_id_fkey FOREIGN KEY (resource_type_id) REFERENCES platform.resource_type(id);
+
+
+--
+-- Name: bid bid_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.bid
+    ADD CONSTRAINT bid_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: bid bid_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.bid
+    ADD CONSTRAINT bid_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: bid bid_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.bid
+    ADD CONSTRAINT bid_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: bid bid_resource_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.bid
+    ADD CONSTRAINT bid_resource_type_id_fkey FOREIGN KEY (resource_type_id) REFERENCES platform.resource_type(id);
+
+
+--
+-- Name: bid_segment bid_segment_bid_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.bid_segment
+    ADD CONSTRAINT bid_segment_bid_id_fkey FOREIGN KEY (bid_id) REFERENCES platform.bid(id);
+
+
+--
+-- Name: configuration configuration_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.configuration
+    ADD CONSTRAINT configuration_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: configuration configuration_created_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.configuration
+    ADD CONSTRAINT configuration_created_by_fkey FOREIGN KEY (created_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: configuration configuration_deleted_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.configuration
+    ADD CONSTRAINT configuration_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: configuration configuration_market_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.configuration
+    ADD CONSTRAINT configuration_market_id_fkey FOREIGN KEY (market_id) REFERENCES platform.market(id);
+
+
+--
+-- Name: cop_limit cop_limit_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit
+    ADD CONSTRAINT cop_limit_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: cop_limit cop_limit_limit_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit
+    ADD CONSTRAINT cop_limit_limit_type_id_fkey FOREIGN KEY (limit_type_id) REFERENCES platform.cop_limit_type(id);
+
+
+--
+-- Name: cop_limit cop_limit_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit
+    ADD CONSTRAINT cop_limit_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: cop_limit cop_limit_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit
+    ADD CONSTRAINT cop_limit_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: cop_limit cop_limit_resource_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_limit
+    ADD CONSTRAINT cop_limit_resource_type_id_fkey FOREIGN KEY (resource_type_id) REFERENCES platform.resource_type(id);
+
+
+--
+-- Name: cop_product cop_product_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_product
+    ADD CONSTRAINT cop_product_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: cop_product cop_product_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_product
+    ADD CONSTRAINT cop_product_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: cop_product cop_product_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_product
+    ADD CONSTRAINT cop_product_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: cop_product cop_product_resource_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_product
+    ADD CONSTRAINT cop_product_resource_type_id_fkey FOREIGN KEY (resource_type_id) REFERENCES platform.resource_type(id);
+
+
+--
+-- Name: cop_status cop_status_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status
+    ADD CONSTRAINT cop_status_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: cop_status cop_status_cop_status_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status
+    ADD CONSTRAINT cop_status_cop_status_type_id_fkey FOREIGN KEY (cop_status_type_id) REFERENCES platform.cop_status_type(id);
+
+
+--
+-- Name: cop_status cop_status_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status
+    ADD CONSTRAINT cop_status_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: cop_status cop_status_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status
+    ADD CONSTRAINT cop_status_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: cop_status cop_status_resource_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.cop_status
+    ADD CONSTRAINT cop_status_resource_type_id_fkey FOREIGN KEY (resource_type_id) REFERENCES platform.resource_type(id);
+
+
+--
+-- Name: input_cop_limit input_cop_limit_cop_limit_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_limit
+    ADD CONSTRAINT input_cop_limit_cop_limit_id_fkey FOREIGN KEY (cop_limit_id) REFERENCES platform.cop_limit(id);
+
+
+--
+-- Name: input_cop_limit input_cop_limit_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_limit
+    ADD CONSTRAINT input_cop_limit_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: input_cop_product input_cop_product_cop_product_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_product
+    ADD CONSTRAINT input_cop_product_cop_product_id_fkey FOREIGN KEY (cop_product_id) REFERENCES platform.cop_product(id);
+
+
+--
+-- Name: input_cop_product input_cop_product_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_product
+    ADD CONSTRAINT input_cop_product_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: input_cop_status input_cop_status_cop_status_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_status
+    ADD CONSTRAINT input_cop_status_cop_status_id_fkey FOREIGN KEY (cop_status_id) REFERENCES platform.cop_status(id);
+
+
+--
+-- Name: input_cop_status input_cop_status_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.input_cop_status
+    ADD CONSTRAINT input_cop_status_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: interval_soc interval_soc_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.interval_soc
+    ADD CONSTRAINT interval_soc_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: interval_soc interval_soc_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.interval_soc
+    ADD CONSTRAINT interval_soc_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: interval_soc interval_soc_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.interval_soc
+    ADD CONSTRAINT interval_soc_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: interval_soc interval_soc_soc_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.interval_soc
+    ADD CONSTRAINT interval_soc_soc_type_id_fkey FOREIGN KEY (soc_type_id) REFERENCES platform.soc_type(id);
+
+
+--
+-- Name: market_agent market_agent_iso_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_agent
+    ADD CONSTRAINT market_agent_iso_id_fkey FOREIGN KEY (iso_id) REFERENCES platform.iso(id);
+
+
+--
+-- Name: market_job market_job_market_job_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_job
+    ADD CONSTRAINT market_job_market_job_type_id_fkey FOREIGN KEY (market_job_type_id) REFERENCES platform.market_job_type(id);
+
+
+--
+-- Name: market_job market_job_market_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_job
+    ADD CONSTRAINT market_job_market_type_id_fkey FOREIGN KEY (market_type_id) REFERENCES platform.market_type(id);
+
+
+--
+-- Name: market market_market_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market
+    ADD CONSTRAINT market_market_type_id_fkey FOREIGN KEY (market_type_id) REFERENCES platform.market_type(id);
+
+
+--
+-- Name: market_permission_grants market_permission_grants_created_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_permission_grants
+    ADD CONSTRAINT market_permission_grants_created_by_fkey FOREIGN KEY (created_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: market_permission_grants market_permission_grants_permission_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_permission_grants
+    ADD CONSTRAINT market_permission_grants_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES platform.permissions(id) ON DELETE RESTRICT;
+
+
+--
+-- Name: market_permission_grants market_permission_grants_user_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_permission_grants
+    ADD CONSTRAINT market_permission_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES platform.users(id);
+
+
+--
+-- Name: market_product_xref market_product_xref_iso_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_product_xref
+    ADD CONSTRAINT market_product_xref_iso_id_fkey FOREIGN KEY (iso_id) REFERENCES platform.iso(id);
+
+
+--
+-- Name: market_product_xref market_product_xref_market_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_product_xref
+    ADD CONSTRAINT market_product_xref_market_id_fkey FOREIGN KEY (market_id) REFERENCES platform.market(id);
+
+
+--
+-- Name: market_product_xref market_product_xref_product_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_product_xref
+    ADD CONSTRAINT market_product_xref_product_id_fkey FOREIGN KEY (product_id) REFERENCES platform.product(id);
+
+
+--
+-- Name: market_task market_task_market_job_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_task
+    ADD CONSTRAINT market_task_market_job_id_fkey FOREIGN KEY (market_job_id) REFERENCES platform.market_job(id);
+
+
+--
+-- Name: market_task market_task_task_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.market_task
+    ADD CONSTRAINT market_task_task_type_id_fkey FOREIGN KEY (task_type_id) REFERENCES platform.task_type(id);
+
+
+--
+-- Name: obligation obligation_award_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_award_id_fkey FOREIGN KEY (award_id) REFERENCES platform.award(id);
+
+
+--
+-- Name: obligation obligation_cop_product_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_cop_product_id_fkey FOREIGN KEY (cop_product_id) REFERENCES platform.cop_product(id);
+
+
+--
+-- Name: obligation obligation_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: obligation obligation_region_award_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.obligation
+    ADD CONSTRAINT obligation_region_award_id_fkey FOREIGN KEY (region_award_id) REFERENCES platform.region_award(id);
+
+
+--
+-- Name: permissions permissions_created_by_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.permissions
+    ADD CONSTRAINT permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES platform.users(id);
+
+
+--
+-- Name: product product_iso_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.product
+    ADD CONSTRAINT product_iso_id_fkey FOREIGN KEY (iso_id) REFERENCES platform.iso(id);
+
+
+--
+-- Name: product product_market_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.product
+    ADD CONSTRAINT product_market_id_fkey FOREIGN KEY (market_id) REFERENCES platform.market(id);
+
+
+--
+-- Name: product product_product_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.product
+    ADD CONSTRAINT product_product_type_id_fkey FOREIGN KEY (product_type_id) REFERENCES platform.product_type(id);
+
+
+--
+-- Name: region_award region_award_market_agent_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region_award
+    ADD CONSTRAINT region_award_market_agent_id_fkey FOREIGN KEY (market_agent_id) REFERENCES platform.market_agent(id);
+
+
+--
+-- Name: region_award region_award_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region_award
+    ADD CONSTRAINT region_award_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: region_award region_award_offer_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region_award
+    ADD CONSTRAINT region_award_offer_type_id_fkey FOREIGN KEY (offer_type_id) REFERENCES platform.offer_type(id);
+
+
+--
+-- Name: region_award region_award_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region_award
+    ADD CONSTRAINT region_award_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: region_award region_award_product_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region_award
+    ADD CONSTRAINT region_award_product_id_fkey FOREIGN KEY (product_id) REFERENCES platform.product(id);
+
+
+--
+-- Name: region_award region_award_region_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region_award
+    ADD CONSTRAINT region_award_region_id_fkey FOREIGN KEY (region_id) REFERENCES platform.region(id);
+
+
+--
+-- Name: region region_iso_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.region
+    ADD CONSTRAINT region_iso_id_fkey FOREIGN KEY (iso_id) REFERENCES platform.iso(id);
+
+
+--
+-- Name: resource resource_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.resource
+    ADD CONSTRAINT resource_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: resource resource_market_agent_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.resource
+    ADD CONSTRAINT resource_market_agent_id_fkey FOREIGN KEY (market_agent_id) REFERENCES platform.market_agent(id);
+
+
+--
+-- Name: resource resource_resource_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.resource
+    ADD CONSTRAINT resource_resource_type_id_fkey FOREIGN KEY (resource_type_id) REFERENCES platform.resource_type(id);
+
+
+--
+-- Name: settlement settlement_asset_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.settlement
+    ADD CONSTRAINT settlement_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES platform.asset(id);
+
+
+--
+-- Name: settlement settlement_market_task_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.settlement
+    ADD CONSTRAINT settlement_market_task_id_fkey FOREIGN KEY (market_task_id) REFERENCES platform.market_task(id);
+
+
+--
+-- Name: settlement settlement_process_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.settlement
+    ADD CONSTRAINT settlement_process_type_id_fkey FOREIGN KEY (process_type_id) REFERENCES platform.process_type(id);
+
+
+--
+-- Name: settlement settlement_resource_type_id_fkey; Type: FK CONSTRAINT; Schema: platform; Owner: -
+--
+
+ALTER TABLE ONLY platform.settlement
+    ADD CONSTRAINT settlement_resource_type_id_fkey FOREIGN KEY (resource_type_id) REFERENCES platform.resource_type(id);
+
+
+--
+-- PostgreSQL database dump complete
+--
+
