version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    environment:
      DB_HOST: your_db_host
      DB_PORT: your_db_port
      DB_NAME: your_db_name
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Detect changed plan files
          id: detect-changed-files
          command: |
            git fetch origin main
            changed_files=$(git diff --name-only origin/main...HEAD | grep -E '\.plan\.yaml$' || true)
            echo "Changed plan files:"
            echo "$changed_files"
            echo "$changed_files" > changed_files.txt
      - run:
          name: Deploy updated plans
          command: |
            . venv/bin/activate
            if [ -s changed_files.txt ]; then
              while IFS= read -r file; do
                if [ -n "$file" ]; then
                  echo "Deploying plan: $file"
                  env=$(echo $file | cut -d'_' -f2 | cut -d'.' -f1)
                  version=$(echo $file | cut -d'_' -f1)
                  python deployer.py -e $env -a deploy -v $version -st all -sch platform
                fi
              done < changed_files.txt
            else
              echo "No .plan.yaml files changed. Skipping deployment."
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
