version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8  # Use the appropriate Python version
    working_directory: ~/repo

jobs:
  deploy:
    executor: python-executor
    parameters:
      git_tag:
        type: string
    environment:
      DB_HOST: 0.tcp.sa.ngrok.io
      DB_PORT: 10492
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            cd tool_deployer
            pip install -e .
      - run:
          name: Deploy schemas
          command: |
            . venv/bin/activate
            echo "Current directory is: $(pwd)"
            ls -la
            echo "Current directory is: $(pwd)"
            echo "Git tag: << parameters.git_tag >>"
            tool_deployer -e caiso -a deploy -v "<< parameters.git_tag >>" -st all -sch platform
      - run:
          name: Configure git
          command: |
            git config --global user.email "circleci@yourdomain.com"
            git config --global user.name "CircleCI"
      - run:
          name: Commit changes
          command: |
            git add .
            git commit -m "Updated plan files with deployment timestamp"
      - run:
          name: Push changes
          command: |
            git push origin $(git rev-parse --abbrev-ref HEAD)

workflows:
  version: 2
  deploy_on_tag:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
          git_tag: ${CIRCLE_TAG}
