version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8  # Use the appropriate Python version
    working_directory: ~/repo

jobs:
  deploy:
    executor: python-executor
    parameters:
      version:
        type: string
        default: ""
      schema:
        type: string
        default: ""
    environment:
      DB_HOST: 0.tcp.sa.ngrok.io
      DB_PORT: 10492
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            cd tool_deployer
            pip install -e .
      - run:
          name: Deploy schemas
          command: |
            . venv/bin/activate
            tool_deployer -e caiso -a deploy -v "<< parameters.version >>" -st all -sch << parameters.schema >>

  commit_and_push:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Configure git
          command: |
            GIT_USER_NAME=$(git config --get user.name || echo "CircleCI")
            GIT_USER_EMAIL=$(git config --get user.email || echo "circleci@yourdomain.com")
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
      - run:
          name: Commit changes
          command: |
            git add .
            git commit -m "Updated plan files with deployment timestamp"
      - run:
          name: Debug and Push changes
          command: |
            echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
            echo "Git status:"
            git status
            echo "Pushing changes..."
            git push origin $(git rev-parse --abbrev-ref HEAD)

workflows:
  version: 2
  deploy_on_tag:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
          version: v0.1.1
          schema: platform
      - commit_and_push:
          requires:
            - deploy
          filters:
            tags:
              only: /^v.*/