version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8  # Use the appropriate Python version
    working_directory: ~/repo

jobs:
  deploy:
    executor: python-executor
    environment:
      DB_HOST: << pipeline.parameters.DB_HOST >>
      DB_PORT: << pipeline.parameters.DB_PORT >>
      DB_NAME: << pipeline.parameters.DB_NAME >>
      DB_USER: << pipeline.parameters.DB_USER >>
      DB_PASSWORD: << pipeline.parameters.DB_PASSWORD >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            cd tool_deployer
            pip install -e .
      - run:
          name: Deploy schemas
          command: |
            . venv/bin/activate
            cd ..
            tool_deployer -e caiso -a deploy -v $(git describe --tags) -st all -sch platform
      - run:
          name: Configure git
          command: |
            git config --global user.email "circleci@yourdomain.com"
            git config --global user.name "CircleCI"
      - run:
          name: Commit changes
          command: |
            git add .
            git commit -m "Updated plan files with deployment timestamp"
      - run:
          name: Push changes
          command: |
            git push origin $(git rev-parse --abbrev-ref HEAD)

workflows:
  version: 2
  deploy_on_tag:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
